---
title: "Recent Minimum Wage Papers"
format:
  html:
    page-layout: full
    link-external-newwindow: true
    css: styles.css
execute:
  echo: FALSE
---

This page displays a list of recent papers mentioning minimum wages, sourced from [OpenAlex](https://openalex.org/), [NBER](https://www.nber.org/papers), and [IZA](https://www.iza.org/publications/dp).

```{r}
#| label: setup
#| include: false
library(readr)
library(reactable)
library(dplyr)
library(htmltools)

min_wage_papers = read_csv("min_wage_papers.csv") |> 
  arrange(desc(publication_date)) |> 
  mutate(publication_date = format(publication_date, "%B %Y")) |> 
  filter(first_retrieved_date >= Sys.Date() - 365)

main_rows = min_wage_papers |> 
  select(authors, publication_date, journal, title)

```

```{r}
#| label: display-table
reactable(
  main_rows,
  columns = list(
    authors = colDef(
      name = "Authors",
      minWidth = 180,
      html = TRUE,
      cell = function(value) {
        formatted_names = sapply(strsplit(value, "; "), function(authors) {
          paste(sapply(authors, function(author) {
            name_parts <- strsplit(author, " ")[[1]]
            name_parts[length(name_parts)]
          }), collapse = ", ")
        })
        sprintf('<div data-label="Authors">%s</div>', formatted_names)
      }
    ),
    publication_date = colDef(
      name = "Publication date",
      minWidth = 150,
      html = TRUE,
      cell = function(value) {
        sprintf('<div data-label="Publication Date">%s</div>', value)
      }
    ),
    journal = colDef(
      name = "Source",
      minWidth = 200,
      html = TRUE,
      cell = function(value, index) {
        work_url = min_wage_papers$doi[index]
        sprintf('<div data-label="Source"><a class="journal-name" href="%s" target="_blank">%s</a></div>', work_url, value)
      }
    ),
    title = colDef(
      name = "Title",
      minWidth = 300,
      html = TRUE,
      cell = function(value) {
        sprintf('<div data-label="Title">%s</div>', value)
      }
    )
  ),
  pagination = FALSE,
  highlight = TRUE,
  borderless = TRUE,
  striped = TRUE,
  defaultPageSize = 100,
  showPageSizeOptions = FALSE,
  class = "reactable-container"
)
```
