name: Update Minimum Wage Papers Data

on:
  schedule:
    - cron: '30 5 * * *' 
  workflow_dispatch: # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
          use-public-rspm: true

      - name: Install R dependencies fetching papers
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Run R script
        run: Rscript min_wage_papers.R
        env:
          OPENALEX_EMAIL: ${{ secrets.OPENALEX_EMAIL }}

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf https://github.com/
          git add min_wage_papers.csv min_wage_papers_to_email.csv
          git commit -m "Update minimum wage papers data" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_GITHUB }}
