name: Update Minimum Wage Papers Data and Deploy Website

on:
  schedule:
    - cron: '0 0 1 * *' # Runs monthly on the first day of the month
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
          R -e "install.packages(c('openalexR', 'dplyr', 'readr', 'purrr', 'tidyr'), repos = 'https://packagemanager.posit.co/cran/latest')"
        shell: bash

      - name: Run R script
        run: Rscript min_wage_papers.R
        env:
          OPENALEX_EMAIL: ${{ secrets.OPENALEX_EMAIL }}

      - name: Commit data changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add min_wage_papers.csv
          git commit -m "Update minimum wage papers data" || echo "No changes to commit"
          git push || echo "No changes to push"

  deploy-website:
    needs: update-data
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install R dependencies for website
        run: |
          R -e "install.packages(c('readr', 'reactable', 'rmarkdown', 'knitr', 'yaml'), repos = 'https://cran.rstudio.com/')"
        shell: bash

      - name: Render Quarto site
        run: quarto render index.qmd

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
