name: Update Minimum Wage Papers Data

on:
  schedule:
    - cron: '0 0 * * 1' # Runs weekly on Mondays at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
          use-public-rspm: true

      - name: Install R dependencies for website
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Run R script
        run: Rscript min_wage_papers.R
        env:
          OPENALEX_EMAIL: ${{ secrets.OPENALEX_EMAIL }}

      - name: Commit data changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add min_wage_papers.csv min_wage_papers_new.csv
          git commit -m "Update minimum wage papers data" || echo "No changes to commit"
          git push || echo "No changes to push"
